### ISSUE TITLE
Error while running

### ISSUE THREAD

**Issue by zgtibu** [landifrancesco/Whatsapp-Automator#1]
it says phone number shared in url is not valid but number is having whatsapp
i think they have changed script

**Comment by landifrancesco** [comment]
Hello, can you share a screen? What mode are you using? Thank you for your report

**Comment by zgtibu** [comment]
using terminal

**Comment by zgtibu** [comment]
![image](https://user-images.githubusercontent.com/69414194/203087017-a7328176-a9ef-4f06-8b0c-2ec02b5e2177.png)

**Comment by zgtibu** [comment]
web.whatsapp is giving error. 
api.whatsapp works but it goes to desktop software.

**Comment by zgtibu** [comment]
Works only with existing chats i think. All other bots giving same error.

**Comment by landifrancesco** [comment]
> using terminal

I think you are using this mode:
Send messages in bulk

Is that correct? Anyway, give me some time, I'll investigate that. I had the same issues attaching a photo to the message but now it's solved.

**Comment by landifrancesco** [comment]
> Works only with existing chats i think. All other bots giving same error.

Could be that you got blocked by these people? I'm just guessing. If you think it would be possibile I could try skipping the message, please try manually to send a message to these people

Please use this URL schema:
https://web.whatsapp.com/send?phone=NUMBERWITHPREFIX&text=TEST

Ovewrite "NUMBERWITHPREFIX" with the phone number in question

I'll wait for your comment then I'll try to fix the issue. Thanks.

**Comment by zgtibu** [comment]
Same error.

**Comment by zgtibu** [comment]
These are new numbers which i am sending for first time.

**Comment by zgtibu** [comment]
Even if it's block it should go to that chat right? Tried api.whatsapp it redirects me but not web.whatsapp link.

**Comment by zgtibu** [comment]
I tried with chrome extension for sending number without saving. same error.

**Comment by landifrancesco** [comment]
> Even if it's block it should go to that chat right? Tried api.whatsapp it redirects me but not web.whatsapp link.

But if you proceed I guess you get the same error right? I think you will always get this error. Which nation are from these numbers?

**Comment by zgtibu** [comment]
91 india

**Comment by landifrancesco** [comment]
> 91 india

Ok so in driver.py line 106 rewrite the line:

`url = 'https://web.whatsapp.com/send?phone=+91' + number.strip() + '&text=' + message`

Now if it works it would proceed, otherwise it would skip the number. Let me know. I have to implement international numbers.

**Comment by zgtibu** [comment]
i tried that also. let me check again.

**Comment by zgtibu** [comment]
Same

**Comment by zgtibu** [comment]
I think web.whatsapp url got changed or something. not bots working at all.

**Comment by landifrancesco** [comment]
> I think web.whatsapp url got changed or something. not bots working at all.

I don't know yet. Try sending messages with a photo and check if it's the same error (I fixed that days ago)

Give me some time to investigate and test.

**Comment by zgtibu** [comment]
i tried with text and attachment. 

it would be great if you can solve it.

**Comment by zgtibu** [comment]
Hi. Now chat and text is coming but after that it is skipping every number.

**Comment by zgtibu** [comment]
Now it's stuck on Please login in Whatsapp Web via QR Code

**Comment by landifrancesco** [comment]
Hello, this is not helping me. I need some photos at least. Or a video. Please send it to my email francesco[[at]]landi[[dot]]work

**Comment by landifrancesco** [comment]
I am not able to replicate the bug

**Comment by zgtibu** [comment]
Please check your mail.

**Comment by landifrancesco** [comment]
I finally replicated the bug, will post an update soon.
Please as soon it will be online download & check again the README.
Let me know if the code does work, thank you.

**Comment by zgtibu** [comment]
Please check your mail.

**Comment by landifrancesco** [comment]
Issue fixed. Thank you for reporting it.
