### ISSUE TITLE
Beginner / how does it work?

### ISSUE THREAD

**Issue by fougiama** [landifrancesco/Whatsapp-Automator#2]
Hello,

I'm a beginner and I can't send a message. I'm on Mac, in Terminal, I put : 

pip3 install -r requirements.txt

My Terminal has installed the necessary applications... Then it shows me 

Default installation by user because normal site-package is not writable.
ERROR: Unable to open requirements file: [Errno 2] No such file or directory : 'requirements.txt
ATTENTION: You are using pip version 21.2.4; however, version 23.3.1 is available.
You should consider upgrading with the command '/Library/Developer/CommandLineTools/usr/bin/python3 -m pip install --upgrade pip'.

Is there a tutorial to explain the installation?

**Comment by landifrancesco** [comment]
Read the new README should be more clear, also the program should be more readable now. Enjoy!
